# Application Name
spring.application.name=backend

# Server
server.port=8080

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.endpoint.info.enabled=true

# OpenAPI / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true

# JWT
jwt.secret=demoSecretKeyThatShouldBeAtLeast256BitsLongForHS256AlgorithmDemo
jwt.expiration-ms=86400000
jwt.refresh-expiration-ms=604800000
