CREATE TABLE fields (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    boundary_geojson TEXT,
    area_hectares DOUBLE PRECISION,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE TABLE monitoring_zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    field_id BIGINT NOT NULL REFERENCES fields(id) ON DELETE CASCADE,
    crop_type VARCHAR(255),
    target_moisture_percentage DOUBLE PRECISION,
    water_allocation_limit_liters DOUBLE PRECISION,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE TABLE edge_nodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id VARCHAR(255) NOT NULL UNIQUE,
    identity_type VARCHAR(50) NOT NULL,
    identity_value VARCHAR(255) NOT NULL,
    mac_address VARCHAR(100),
    serial_number VARCHAR(100),
    lifecycle_state VARCHAR(50) NOT NULL,
    health_state VARCHAR(50) NOT NULL,
    battery_level DOUBLE PRECISION,
    solar_voltage DOUBLE PRECISION,
    signal_dbm INTEGER,
    last_heartbeat TIMESTAMP,
    monitoring_zone_id BIGINT REFERENCES monitoring_zones(id) ON DELETE SET NULL,
    hardware_model VARCHAR(255),
    firmware_version VARCHAR(100),
    version BIGINT DEFAULT 0 NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE TABLE monitoring_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    monitoring_zone_id BIGINT NOT NULL REFERENCES monitoring_zones(id) ON DELETE CASCADE,
    edge_node_id BIGINT REFERENCES edge_nodes(id) ON DELETE SET NULL,
    primary_sensor_type VARCHAR(50) NOT NULL,
    depth_cm DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE TABLE telemetry_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monitoring_point_id BIGINT NOT NULL REFERENCES monitoring_points(id) ON DELETE CASCADE,
    edge_node_id BIGINT REFERENCES edge_nodes(id) ON DELETE SET NULL,
    sensor_type VARCHAR(50) NOT NULL,
    value_num DOUBLE PRECISION NOT NULL,
    unit VARCHAR(50) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE irrigation_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edge_node_id BIGINT NOT NULL REFERENCES edge_nodes(id) ON DELETE CASCADE,
    decision_type VARCHAR(50) NOT NULL,
    trigger_reason VARCHAR(50) NOT NULL,
    requested_duration_minutes INTEGER,
    requested_volume_liters DOUBLE PRECISION,
    execution_status VARCHAR(50) NOT NULL,
    node_timestamp TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE auto_irrigation_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edge_node_id BIGINT UNIQUE REFERENCES edge_nodes(id) ON DELETE CASCADE,
    schedule_mode VARCHAR(50) NOT NULL,
    min_soil_moisture_percentage DOUBLE PRECISION,
    max_soil_moisture_percentage DOUBLE PRECISION,
    max_single_run_minutes INTEGER,
    safety_rain_override BOOLEAN DEFAULT TRUE,
    cron_schedule VARCHAR(100),
    version BIGINT DEFAULT 0 NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE TABLE irrigation_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    actor VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id VARCHAR(100) NOT NULL,
    payload_json TEXT,
    created_at TIMESTAMP NOT NULL
);

-- Time-Series and Query Indexes
CREATE INDEX idx_telemetry_point_time ON telemetry_readings(monitoring_point_id, timestamp DESC);
CREATE INDEX idx_decision_node_time ON irrigation_decisions(edge_node_id, node_timestamp DESC);
CREATE INDEX idx_node_zone_status ON edge_nodes(monitoring_zone_id, health_state);
CREATE INDEX idx_audit_entity_time ON irrigation_audit_logs(entity_type, entity_id, created_at DESC);

